### PR TITLE
Use offline RTDB refs for testing

### PR DESCRIPTION
**Pull request by tstirrat**

### CODE REVIEW

**Comment by ultrasaurus** [comment]
this looks nice!  

@jenmei -- want to take a look before I merge?

**Review by jenmei — APPROVED** [review]
Looks good to me! If the code for the fake db comes from somewhere else, let's credit it, but it could be in a subsequent commit.

**Comment by tstirrat** [comment]
I've updated this to use `firebase-admin` instead of `firebase`, removed dependency, added license info. Please LGTM and I will merge

**Comment by tstirrat** [comment]
For some reason the `mocha test` command is not running in the latest test.

**Comment by tstirrat** [comment]
Retest this please!

**Comment by tstirrat** [comment]
Closing and re-opening to trigger a new build

**Comment by tstirrat** [comment]
Tests ran this time!

@jenmei ready to merge :)

**Comment by jenmei** [comment]
@tstirrat Great! Looks good to me, merging …

**Pull request merged**
