### PR TITLE
login screen

### PR DESCRIPTION
**Pull request by berlinjohnson**
If user isn't logged in they see login screen like in mobile app.  

Builds off first "vizD first pass" PR

### CODE REVIEW

**Comment by berlinjohnson** [comment]
Still needs work and is failing things, but styles are there:

**Logged out, unknown auth state, logged in:**
screen shot 2017-05-09 at 1 36 27 pm

**Comment by berlinjohnson** [comment]
login

**Comment by berlinjohnson** [comment]
@ultrasaurus this one is failing still and I'm not sure why, but moves login to login component and hides toolbar if not logged in as seen in gif above

**Comment by ultrasaurus** [comment]
FYI: the most recent test failure was from a stale github token on travis.  I updated it an re-ran the tests and all is good, so will merge this!

**Pull request merged**
